#!python3

import argparse

from app.main import Main


parser = argparse.ArgumentParser(description='Process some integers.')
# TODO get the modes dynamically
parser.add_argument('mode', type=str,
                    help='the fetch mode to use (reddit_next, archive)')
parser.add_argument('target', type=str,
                    help='the target story or document containing list of stories (URL, reddit ID, etc)')

parser.add_argument('--no-archive', dest='archive', action='store_false', default=True,
                    help='do not write the story to the archive')

args = parser.parse_args()

Main(args).run()
